import prods from '../../../csvjson.json';
import { v4 as uuidv4 } from 'uuid';
export const TestProducts = prods.slice(0, 200).map(p => ({
    ...p,
    actual_price: p.actual_price.replace(/[₹,]/g, ''),
    discount_price: p.discount_price.replace(/[₹,]/g, ''),
    id: uuidv4(),
    quantity: 1,
    warranty: 1,
}));
export const allProducts = [...TestProducts];
export const locations = [
    "New York",
    "London",
    "Paris",
    "Tokyo",
    "Sydney",
    "Berlin",
    "Moscow",
    "Rio de Janeiro",
    "Cape Town",
    "Toronto",
    "Dubai",
    "Singapore",
    "Barcelona",
    "Rome",
    "Amsterdam",
    "Mumbai",
    "Seoul",
    "Buenos Aires",
    "Mexico City",
    "Cairo",
    "Bangkok",
    "Istanbul",
    "San Francisco",
    "Los Angeles",
    "Chicago",
    "Hong Kong",
    "Lagos",
    "Lisbon",
    "Stockholm",
    "Vienna",
    "Jakarta",
    "Kuala Lumpur",
    "Athens",
    "Helsinki",
    "Budapest",
    "Warsaw",
    "Prague",
    "Melbourne",
    "Brussels",
    "Vancouver",
    "Montreal",
    "Dublin",
    "Zurich",
    "Oslo",
    "Copenhagen",
    "Auckland",
    "Manila",
    "Lima",
    "Bogotá",
];
